/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    checkstyle
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.0")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.9.0")
    testImplementation("org.assertj:assertj-core:3.23.1")
    implementation("org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
}

checkstyle {
    toolVersion = "10.3.3"
}

application {
    // Define the main class for the application.
    mainClass.set("job4j_elementary_gradle.App")
}

tasks.test {
    useJUnitPlatform()
}
